# Site settings
author: Alison Reilly
title: The Daily Code
header-img: img/home-bg.png
email: reillyamr@gmail.com
copyright_name: Alison Reilly
description: > # this means to ignore newlines until "baseurl:"
  A blog reflecting progress towards full stack web development
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Tsunamins

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
